### ISSUE TITLE
支持dubbo查询聚合

### ISSUE THREAD

**Issue by alangchen** [spring-avengers/tesla#6]
目前不支持dubbo查询聚合支持
1. 支持多个调用dubbo的聚合支持 
2. 支持直接路由， springcloud 和dubbo 接口集合支持

**Comment by linking12** [comment]
@alangchen Dubbo的查询聚合的话，可以自定义Filter来做，一个暴露出去的http请求，可以对应多个Dubbo请求；
这种的需求的话，场景比较少见，建议自己个性化定制比较好；

**Comment by alangchen** [comment]
这种对于后端的项目都是dubbo还是比较多，也不会去新建http服务去聚合
所有开发一个可以聚合dubbo和http的功能 之前的dubbo调用时直接返回其实和http处理流程还是有不同，由于和http聚合所以dubbo的调用修改成和http统一的流程，另外就是和http不同的是这里的dubbo 配置根据服务名和路径去引用一个已有的配置
client -> proxy ->call dubbo  
                          ->call http server
                          
![image](https://user-images.githubusercontent.com/10444153/57900162-5c438d00-7892-11e9-9a9a-8e253fe092d3.png)
![image](https://user-images.githubusercontent.com/10444153/57900285-d116c700-7892-11e9-80b3-01876597e9ec.png)

**Comment by linking12** [comment]
@alangchen 我明白你的意思了，你想同时具备Dubbo和Http聚合的能力，这个个人觉得比较难以推行，我认为在一个公司仅会存在一个服务化框架，不可能存在多套

**Comment by alangchen** [comment]
一般情况应该不会有2种服务框架， 这种情况存在新老服务，比如以前用springcloud 后来转dubbo，这个混合不支持问题不大
